### ISSUE TITLE
Forcing the light theme

### ISSUE THREAD

**Issue by jared252016** [nileane/TangerineUI-for-Mastodon#117]
I recently upgraded to Mastodon v4.3.0 and for some reason it's forcing the light theme regardless of what is set as the default theme. I'm using the custom.css approach to setting the theme. I'm using Tangerine UI v2.0.

I made a few modifications, like changing the logo, but it seems that even with reverting back to the original css from Github it still does the same thing. 

Any advice would be appreciated. Is there a cache or something from Mastodon / javascript? How is it setting the default theme? 

I have cleared my browser cache and made sure Cloudflare Development Mode is enabled while testing. It does load the theme, it's just the light version of the theme. I need the dark and Mastodon (Dark) is setting in site admin.

**Comment by nileane** [comment]
Tangerine UI uses the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media feature to detect if you have requested a light or dark theme through an operating system setting or a user agent setting. [(As indicated in the README](https://github.com/nileane/TangerineUI-for-Mastodon/issues/117#user-content-fnref-1-fa845613a396693bdf2b7b00831cc466)

If you're seeing the light theme version of the theme, it probably means that your browser or operating system is set to light mode instead of dark mode.

**Comment by raphgilles** [comment]
> I recently upgraded to Mastodon v4.3.0 and for some reason it's forcing the light theme regardless of what is set as the default theme. I'm using the custom.css approach to setting the theme. I'm using Tangerine UI v2.0.
> 
> I made a few modifications, like changing the logo, but it seems that even with reverting back to the original css from Github it still does the same thing.
> 
> Any advice would be appreciated. Is there a cache or something from Mastodon / javascript? How is it setting the default theme?
> 
> I have cleared my browser cache and made sure Cloudflare Development Mode is enabled while testing. It does load the theme, it's just the light version of the theme. I need the dark and Mastodon (Dark) is setting in site admin.

I had the same needs. My solution was to install a plugin that allowed me to set the "prefers-color-scheme" website by website.
https://github.com/rugk/website-dark-mode-switcher/
