### ISSUE TITLE
"Member since" missing on profile

### ISSUE THREAD

**Issue by ThomasNeubauer** [nileane/TangerineUI-for-Mastodon#120]
Hi,

thanks for the awesome design! 

Our instance uses v2.1 and i discovered that on profiles the "Member since" is not shown. Is this a design choice?
I think it is interesting to see, how old a mastodon account is and would like to have that option in Tangerine.

**Comment by nileane** [comment]
Hi,

This was a deliberate choice that I made early on when I started working on the theme. My opinion on this is that this is an unreliable piece of information that doesn't properly reflect how long someone has been present on Mastodon/the Fediverse, since it doesn't take instance migrations into account.

Do you still think I should add it back?
