### ISSUE TITLE
Small misalignments with Mastodon v4.3.2

### ISSUE THREAD

**Issue by thomas-pike** [nileane/TangerineUI-for-Mastodon#135]
On a wide screen, the top border is now missing on the main feed:
![2024-12-03 17 46 51 social testvivaldi tech cf968690ccd0](https://github.com/user-attachments/assets/14c8ba20-e407-4aff-9712-0e99e6c4ad54)
On a narrower screen (single column display), the `Home` text now overlaps the first post.
![2024-12-03 17 47 56 social testvivaldi tech bded61b2916d](https://github.com/user-attachments/assets/b5132bf5-4052-48ab-8ad4-ccd94392b089)
These both seem to be caused by changes between Mastodon v4.3.1 and v4.3.2.

**Comment by ClearlyClaire** [comment]
This is most likely caused by `contain: inline-size layout paint style` that we recently added on `.columns-area__panels__main` to fix an issue with sizing of certain elements.

`contain: inline-size` would suffice for this fix the initial issue, and I think it would restore TangerineUI's ability to do its tricks

**Comment by thomas-pike** [comment]
I can confirm that adding
```
.columns-area__panels__main {
    contain: inline-size;
}
```

appears to fix the issues.

**Comment by nileane** [comment]
Thanks friends!
