### ISSUE TITLE
Add support for the new link preview cards

### ISSUE THREAD

**Issue by tcitworld** [nileane/TangerineUI-for-Mastodon#52]
The text of the preview card looks really aligned to the left.

Using glich-soc 3b49b5a
TangerineUI 942a55a

![image](https://github.com/nileane/TangerineUI-for-Mastodon/assets/2197836/8f176aeb-059f-4a2f-b66b-acbce52b671c)

**Comment by nileane** [comment]
Yep I'm aware.

This new design for link preview cards has not yet shipped in Mastodon stable. It's only available in nightlies. Glich-soc instances also have it since they're ahead on Mastodon releases.

Unfortunately I can't fix this for now without breaking the current design for link previews, so I will have to wait until this has shipped for everyone in stable (probably in Mastodon 4.2 I guess)

Sorry.
Will keep you updated in this issue.

**Comment by nileane** [comment]
Update on this matter: I'm currently working on adding support for the new link previews and other new web features coming in Mastodon v4.2 (now released in beta). I will release all of those when v4.2 is officially released :)

**Comment by nileane** [comment]
Done :) https://github.com/nileane/TangerineUI-for-Mastodon/commit/c9db752344e770d7346cfbd2d89688d211fd4478
