### ISSUE TITLE
Individual lists aren't highlighted correctly?

### ISSUE THREAD

**Issue by thibaultmol** [nileane/TangerineUI-for-Mastodon#84]
I think this is a bug or is it intentional?
![image](https://github.com/nileane/TangerineUI-for-Mastodon/assets/1010226/88f2c784-eefb-4449-81ba-ae30656d139e)
I would expect the highlighted rounded rectangle to go over the entire list name including the list icon

**Comment by nileane** [comment]
Hi, please make sure you are using the correct version of Tangerine UI for your Mastodon instance: https://github.com/nileane/TangerineUI-for-Mastodon?tab=readme-ov-file#compatibility

**Comment by thibaultmol** [comment]
Should have mentoined, sorry

I'm using 
https://github.com/nileane/TangerineUI-for-Mastodon/blob/main/TangerineUI-purple.css
On our mastodon instance en.osm.town (v4.2.7)

**Comment by nileane** [comment]
As indicated in the Compatibility section in the README, since en.osm.town is running on Mastodon v4.2.7, you should be using Tangerine UI Legacy, not the latest version which is only compatible with Mastodon 4.3 and above.

(So you should be using this version, specifically: https://github.com/nileane/TangerineUI-for-Mastodon/blob/legacy/TangerineUI-purple.css)

**Comment by thibaultmol** [comment]
OH sorry, misread the numbers. 
Yep that works, sorry
